vars: {
  d2-config: {
    layout-engine: elk
    # Terminal theme code
    theme-id: 300
  }
}

users: {
  shape: person
  style.multiple: true
}

server: {
  docker network: {
    nginx: {
      shape: diamond
    }
    frontend: {
      shape: page
    }
    go-api

    postgres: {
      shape: cylinder
      style.multiple: true
    }

    nginx -> go-api: request
    nginx -> frontend: fetch
    go-api -> postgres: data
  }

  storage: {
    shape: stored_data
  }

  docker network.postgres -> storage: persist
}

users -> server.docker network.nginx: request
