# Root
client: {
  user: {
    shape: person
  }
  user -> web browser
}

server: {
  docker network: {
    nginx: {
      shape: diamond
    }
    frontend: {
      shape: page
    }
    go-api

    postgres: {
      production: {
        shape: cylinder
      }
      test: {
        shape: cylinder
      }
    }

    nginx -> go-api: /api
    nginx -> frontend: /
    go-api -> postgres: sql

    postgres -> go-api -> nginx: data
  }
  storage: {
    pg_data: {
      shape: stored_data
    }
  }
  docker network.postgres -> storage.pg_data: persist
  storage -> docker network: docker-compose
}

client.web browser -> server.docker network.nginx: request
server.docker network.frontend -> server.docker network.nginx -> client.web browser: display
direction: right
